export function validateEmail(email) {
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return false;
    }
    
    const blockedDomains = [
      'mailinator.com',
      'tempmail.com',
      '10minutemail.com',
      'guerrillamail.com',
      'yopmail.com',
      'throwawaymail.com',
      'fakeinbox.com',
      'trashmail.com',
      'maildrop.cc',
      'temp-mail.org',
      'dispostable.com',
      'getnada.com',
      'mailnesia.com',
      'mohmal.com',
      'tempail.com',
      'harakirimail.com',
      'grr.la',
      'mailmetrash.com',
      'trashmailer.com',
      'spamgourmet.com',
      'mailcatch.com',
      'discard.email',
      'mailmoat.com',
      'mailinator.net',
      'mailinator.org',
      'notmailinator.com',
      'sogetthis.com',
      'spamherelots.com',
      'thisisnotmyrealemail.com',
      'zippymail.info',
      'filzmail.com',
      'incognitomail.com',
      'anonymousemail.me',
      'jetable.org',
      'mailnull.com',
      'mytrashmail.com',
      'tempinbox.com',
      'trash-mail.com',
      'trashmail.de',
      'trashmail.me',
      'trashmail.net',
      'trashmail.ws',
      'dodgit.com',
      'dodgeit.com',
      'emailias.com',
      'fake-mail.com',
      'mailforspam.com',
      'mailimate.com',
      'mintemail.com',
      'spambob.net',
      'spambog.com',
      'spambog.de',
      'spambox.us',
      'tempemail.net',
      'tempemailaddress.com',
      'tempmailaddress.com',
      'thankyou2010.com',
      'wegwerfemail.de'
    ];
    
    const domain = email.split('@')[1].toLowerCase();
    return !blockedDomains.includes(domain);
  }